### ISSUE TITLE
Create a separate list for books, booklets, tutorials, blogs, videos, and other forms of documentation

### ISSUE THREAD

**Issue by olekscode** [pharo-open-documentation/awesome-pharo#121]
Right now it is mixed with software libraries, and I think that the list would be cleaner if we had:
- awesome-pharo
- awesome-pharo-documentation

**Comment by juliendelplanque** [comment]
If it gets bigger, maybe.
But for now, I would keep it like that, else we will quickly need a meta-list for all the lists we can do...
I think it is overkill for now.
What do you think @jecisc ?

**Comment by jecisc** [comment]
I agree that we should wait a little before starting meta-lists

**Comment by jecisc** [comment]
Or we can create one if someone starts it with already a lot of content.
