### ISSUE TITLE
Add MaterialComponentsWeb in web section

### ISSUE THREAD

**Issue by sanjayminni** [pharo-open-documentation/awesome-pharo#146]
Add MaterialComponentsWeb in the web section

https://github.com/yannij/MaterialComponentsWeb

**Comment by labordep** [comment]
Hi @sanjayminni, your repository description have a mention "!! NOT MAINTAINED !!".
But it appears renctly update, what is the status of this project?

**Comment by sanjayminni** [comment]
MaterialComponentsWeb (Material UI by Google) and this adaptor (by yannij)  will unlikely be maintained. The last update was just a small sanitisation.  Tha packages authour (yannij) has tranformed the code to an interface for another framework (Quasar) https://github.com/yannij/Seaside-Quasar. You may check with him if he intends to maintain that

**Comment by labordep** [comment]
Thanks @sanjayminni!
 @jecisc I think we can close this issue.

**Comment by jecisc** [comment]
Thanks
